### PR TITLE
View integration

### PR DESCRIPTION
**Pull request by Wubuntu88**
This update integrates everything.  You will be able to play a game of checkers.  If there are any problems let me know.  I'm sure we will want to tweak it in the future.

Will

### CODE REVIEW

**Comment by stefprez** [comment]
Could you remove the .orig files from this PR? No need to have these included!

**Comment by Wubuntu88** [comment]
hm ok I didn't know those were included.  Should I cancel the pull request, remove them from my fork and do another pull request?

**Comment by stefprez** [comment]
Nope, you can just delete them from your branch and commit the changes
deleting the files up and the pull request will pick up the new commit
automatically, as long as you do it on the same branch as the pull request!

**Comment by csperlich** [comment]
I'm merging it in!

**Comment by stefprez** [comment]
Sounds good!

**Pull request merged**
